<h1>Test</h1>
<hr>
Hello <?= $this->name ?>
<hr>
Test:
<ul>
	<li><a href="<?= $this->url('test', ['action' => 'test']) ?>">Test</a> (enter "name" param in URL)</li>
	<li><a href="<?= $this->url('test', ['action' => 'request']) ?>">Request</a></li>
	<li><a href="<?= $this->url('test', ['action' => 'panic']) ?>">Panic</a></li>
	<li><a href="<?= $this->url('test', ['action' => 'day-week-month']) ?>">Day/Week/Month</a></li>
	<li><a href="<?= $this->url('test', ['action' => 'redirect']) ?>">Redirect</a></li>
	<li><a href="<?= $this->url('test', ['action' => 'time']) ?>">Time Service</a></li>
	<li><a href="<?= $this->url('test', ['action' => 'nested-view-models']) ?>">Nested View Models</a></li>
	<li><a href="<?= $this->url('test', ['action' => 'service-test']) ?>">Service Test</a></li>
	<li><a href="<?= $this->url('test', ['action' => 'terminal']) ?>">Terminal</a></li>
	<li><a href="<?= $this->url('test', ['action' => 'json-default']) ?>">JSON Using Default Renderer</a></li>
	<li><a href="<?= $this->url('test', ['action' => 'json-model']) ?>">JSON Using JsonModel</a></li>
	<li><a href="<?= $this->url('test', ['action' => 'vars']) ?>">Vars Container</a></li>
	<li><a href="<?= $this->url('test', ['action' => 'event']) ?>">Event Test</a></li>
	<li><a href="<?= $this->url('test', ['action' => 'adapter']) ?>">Adapter Test</a></li>
</ul>
